/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.caminhao;

import dao.CaminhaoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Caminhao;

/**
 *
 * @author User
 */
public class TelaCaminhao extends javax.swing.JFrame {

    /**
     * Creates new form TelaCaminhao
     */
    public TelaCaminhao() {
        initComponents();
       carregarTabelaCaminhoes("Todos"); // Exibe todos os caminhões por padrão
}
    
    
    
    public void carregarTabelaCaminhoes(String filtro) {
    CaminhaoDAO caminhaoDAO = new CaminhaoDAO();
    List<Caminhao> caminhoes = caminhaoDAO.listarTodos(); // Recupera todos os caminhões

    DefaultTableModel model = (DefaultTableModel) tbMotoristas.getModel();
    model.setRowCount(0); // Limpa a tabela

    for (Caminhao caminhao : caminhoes) {
        boolean disponivel = caminhao.getDisponivel() != null && caminhao.getDisponivel();

        // Aplica o filtro
        if ("Disponíveis".equals(filtro) && !disponivel) {
            continue;
        }
        if ("Indisponíveis".equals(filtro) && disponivel) {
            continue;
        }

        model.addRow(new Object[] {
            caminhao.getId(),
            caminhao.getMotorista(),
            caminhao.getCarga() == null ? "Sem carga" : caminhao.getCarga(),
            disponivel // O valor booleano será renderizado como "true" ou "false"
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCaminhao = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMotoristas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCaminhao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCaminhao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaminhao.setText("Caminhão");

        jButton3.setText("Criar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbMotoristas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Motorista", "Carga", "Disponível"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMotoristas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMotoristasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMotoristas);
        if (tbMotoristas.getColumnModel().getColumnCount() > 0) {
            tbMotoristas.getColumnModel().getColumn(0).setResizable(false);
            tbMotoristas.getColumnModel().getColumn(1).setResizable(false);
            tbMotoristas.getColumnModel().getColumn(2).setResizable(false);
            tbMotoristas.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setText("Filtrar por:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Disponíveis", "Indisponíveis"}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCaminhao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCaminhao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TelaNovoCaminhao telaNovoCaminhao = new TelaNovoCaminhao();
        telaNovoCaminhao.setVisible(true);
        telaNovoCaminhao.addWindowListener(new java.awt.event.WindowAdapter() {
        
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            carregarTabelaCaminhoes("Todos"); // Atualiza a tabela
        }
    });
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     int linhaSelecionada = tbMotoristas.getSelectedRow();
    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um caminhão para editar!", "Erro", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int id = (int) tbMotoristas.getValueAt(linhaSelecionada, 0);
    CaminhaoDAO caminhaoDAO = new CaminhaoDAO();
    Caminhao caminhao = caminhaoDAO.buscarPorId(id);

    if (caminhao != null) {
        TelaEditarCaminhao telaEditarCaminhao = new TelaEditarCaminhao(caminhao);
        telaEditarCaminhao.setVisible(true);
        telaEditarCaminhao.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                carregarTabelaCaminhoes("Todos"); // Atualiza a tabela ao fechar a tela de edição
            }
        });
    } else {
        JOptionPane.showMessageDialog(this, "Caminhão não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Verifica se uma linha foi selecionada
    int linhaSelecionada = tbMotoristas.getSelectedRow();
    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um caminhão para remover!", "Erro", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Obtém o ID do caminhão selecionado
    int id = (int) tbMotoristas.getValueAt(linhaSelecionada, 0);

    // Confirma a exclusão
    int confirmacao = JOptionPane.showConfirmDialog(
        this, 
        "Tem certeza de que deseja remover este caminhão?", 
        "Confirmação de exclusão", 
        JOptionPane.YES_NO_OPTION
    );

    if (confirmacao == JOptionPane.YES_OPTION) {
        // Chama o DAO para remover o caminhão
        CaminhaoDAO caminhaoDAO = new CaminhaoDAO();
        boolean sucesso = caminhaoDAO.remover(id);

        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Caminhão removido com sucesso!");
            carregarTabelaCaminhoes("Todos"); // Atualiza a tabela
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao remover o caminhão!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbMotoristasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMotoristasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbMotoristasMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String filtroSelecionado = (String) jComboBox1.getSelectedItem();
        carregarTabelaCaminhoes(filtroSelecionado);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCaminhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCaminhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCaminhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCaminhao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCaminhao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCaminhao;
    private javax.swing.JTable tbMotoristas;
    // End of variables declaration//GEN-END:variables
}
